### ISSUE TITLE
Create new nurse

### ISSUE THREAD

**Issue by Jinninni040507** [santiestebanellc/nurse_project#16]
### Create new nurse
<hr>
This function has to include corresponding <b>status code</b> based on result if <code>createNewNurse()</code> is <b>successful</b> or <b>not</b>. 
<br><br>
Status Codes:
<br>
  -  Created -> <code>201 OK</code>
<br>
  -  Error -> <code>400 KO</code>

**Comment by santiestebanellc** [comment]
Implemented in development.
