### ISSUE TITLE
Delete nurse by Id

### ISSUE THREAD

**Issue by Jinninni040507** [santiestebanellc/nurse_project#19]
### Delete nurse by id
<hr>
This function has to include corresponding <b>status code</b> based on result if <code>deleteNurseById()</code> is <b>successful</b> or <b>not</b>. 
<br><br>
Status Codes:
<br>
  -  Created -> <code>200 OK</code>
<br>
  -  Error -> <code>404 KO</code>

**Comment by santiestebanellc** [comment]
Implemented in development.
