### ISSUE TITLE
Include corresponding status code based on result if nurse is found or not by name

### ISSUE THREAD

**Issue by Japoivvb** [santiestebanellc/nurse_project#9]
https://github.com/santiestebanellc/nurse_project/blob/6926c9622201d80f2cca2330dbb0f3c11c2db4c1/src/Controller/NurseController.php#L59

doc
https://github.com/symfony/symfony/blob/06d1b76febc6299c9ed1d7ec71f15fa138f11ce6/src/Symfony/Component/HttpFoundation/Response.php#L22

**Comment by santiestebanellc** [comment]
Implemented in development.
